version: '3'
services:
  api:
    image: flagship-store-api
    build: .
    networks:
      - backend
    ports:
      - "3080:3080"
    volumes:
      - ./:/usr/src/app

  web-cli:
    image: flagship-store-api
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge